name: sample_database
description: Basic sample demonstating minimal setup for flutter_kore - here we are using http, DI, and navigation components. Combined with simple object box db implementation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_kore: ^1.4.6

  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3
  objectbox: ^5.0.2
  objectbox_flutter_libs: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter

  flutter_kore_generator: ^2.3.0

  json_serializable:
  build: ^4.0.0
  build_config: ^1.2.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  objectbox_generator: ^5.0.2
  flutter_lints: ^6.0.0
  test:

flutter:
  uses-material-design: true