name: example
description: Basic example
version: 1.1.0
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: 3.35.6

dependencies:
  flutter:
    sdk: flutter

  flutter_kore: ^1.4.7

  dio: ^5.9.0
  dart_mappable: ^4.6.1

dev_dependencies:
  build: ^4.0.3
  build_config: ^1.2.0
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  dart_mappable_builder: ^4.6.1
  analyzer: ^8.4.1

  flutter_kore_generator: ^2.3.0

flutter:
  uses-material-design: true