name: sample_basic
description: Basic sample demonstating minimal setup for flutter_kore - here we are using only http and DI components.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: 3.38.2

dependencies:
  flutter:
    sdk: flutter

  dart_mappable: ^4.6.1
  dio: ^5.9.0
  flutter_kore: ^1.4.6
  shared_preferences: ^2.5.3

dev_dependencies:
  build: ^4.0.3
  build_config: ^1.2.0
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.1
  flutter_kore_generator: ^2.3.0
  flutter_lints: ^6.0.0
  test:

flutter:
  uses-material-design: true